### ISSUE TITLE
model.py num_simulations is hardcoded

### ISSUE THREAD

**Issue by icgray** [onestr1/peen-ml#1]
Input to `def create_data_loaders(base_folder, num_simulations, load_files=("checkerboard", "displacements"), skip_missing=True, batch_size=15):` num_simulations is hardcoded based on dataset, should be dynamically assigned.

Value is hardcoded in main `num_simulations1 = 1531  # change the number of simulatiions to your actual data size`

**Comment by JiachenJasonZhong** [comment]
I will look into it
